# Generated by Django 3.1.7 on 2021-04-03 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessinformation',
            old_name='physical_address',
            new_name='business_physical_address',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='physical_address',
            new_name='personal_physical_address',
        ),
    ]
