# Generated by Django 3.1.7 on 2021-06-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210503_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
