# Generated by Django 3.1.7 on 2021-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210720_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinformation',
            name='business_as',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='business_physical_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='date_of_establishment',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='duns',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='extenstion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='sic_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='type_of_ownership',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='zip',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
