# Generated by Django 3.1.7 on 2021-07-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210720_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinformation',
            name='financing_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
