# Generated by Django 3.1.7 on 2021-07-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210720_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpimetrics',
            name='current_ap',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kpimetrics',
            name='current_ar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kpimetrics',
            name='current_bank_balance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kpimetrics',
            name='ytd_profit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kpimetrics',
            name='ytd_revenue',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
