# Generated by Django 3.1.7 on 2021-08-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210720_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='form_step',
            field=models.IntegerField(null=True),
        ),
    ]
