# Generated by Django 3.1.7 on 2021-08-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210805_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='birthday',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
