# Generated by Django 3.1.7 on 2021-09-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_businessinformation_ein'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='personal_physical_address',
            new_name='home_address_1',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='home_address_2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
