# Generated by Django 3.1.7 on 2021-09-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210901_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='zip',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
