# Generated by Django 3.1.7 on 2021-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210913_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='state_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
