# Generated by Django 3.1.7 on 2021-12-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_personalinformation_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='state_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
