# Generated by Django 3.1.7 on 2021-10-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_plans_userplan_userplanhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='subcribed_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
