# Generated by Django 3.1.7 on 2021-10-28 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_auto_20211015_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderWriteDetails',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
