# Generated by Django 3.1.7 on 2021-10-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_underwritedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='underwritedetails',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
