# Generated by Django 3.1.7 on 2021-11-24 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_underwritedetails_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('One Page Executive Summary', 'executive_summary'), ('Business Plan', 'business_plan'), ('Projected Financial Statements', 'projected_financial_statements'), ('Pitch Deck', 'pitch_deck'), ('Resume', 'resume'), ('Other', 'other')], max_length=50)),
                ('path', models.FileField(upload_to='user_documentation/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_picture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_documentation',
            },
        ),
    ]
