# Generated by Django 3.1.7 on 2021-12-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_userdocumentation'),
        ('core', '0025_businessinformation_state_code'),
    ]

    operations = [
    ]
