stages:
  - build
  - deploy
build job:
  stage: build
  script:
    - export PYTHONPATH=.
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip install -r requirements.txt
deploy job:
  stage: deploy
  variables:
    DEPLOYMENT_DATA: '{"app_name":"Gro API", "password":"SuperSecret"}'
    DEPLOYMENT_DATA_TYPE: "Content-Type: application/json"
  script:
    - apt-get update -qy
    - apt-get install curl -y
    - curl -d $DEPLOYMENT_DATA -H $DEPLOYMENT_DATA_TYPE -X POST http://18.233.153.200/deployment
    
  
