# Generated by Django 3.1.7 on 2021-11-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crs',
            name='consumer_credit_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
