# Generated by Django 3.1.7 on 2021-07-08 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freshbooks_app', '0002_freshbooksprofitloss_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshbooksprofitloss',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
