# Generated by Django 3.1.7 on 2021-10-15 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_auto_20211015_1136'),
        ('freshbooks_app', '0003_auto_20210708_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_profit_ytd', models.FloatField(default=0)),
                ('net_profit_py_1', models.FloatField(default=0)),
                ('net_profit_py_2', models.FloatField(default=0)),
                ('net_profit_p_3', models.FloatField(default=0)),
                ('gross_profit_py_1', models.FloatField(default=0)),
                ('gross_profit_py_2', models.FloatField(default=0)),
                ('gross_profit_py_3', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AccountMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cogs_ytd', models.FloatField(default=0)),
                ('cogs_py_1', models.FloatField(default=0)),
                ('cogs_py_2', models.FloatField(default=0)),
                ('cogs_py_3', models.FloatField(default=0)),
                ('shareholder_equity_py_1', models.FloatField(default=0)),
                ('shareholder_equity_py_2', models.FloatField(default=0)),
                ('shareholder_equity_py_3', models.FloatField(default=0)),
                ('working_capital_py_1', models.FloatField(default=0)),
                ('working_capital_py_2', models.FloatField(default=0)),
                ('working_capital_py_3', models.FloatField(default=0)),
                ('cash_in_py_1', models.FloatField(default=0)),
                ('cash_in_py_2', models.FloatField(default=0)),
                ('cash_in_py_3', models.FloatField(default=0)),
                ('cash_out_py_1', models.FloatField(default=0)),
                ('cash_out_py_2', models.FloatField(default=0)),
                ('cash_out_py_3', models.FloatField(default=0)),
                ('cash_closing_py_1', models.FloatField(default=0)),
                ('cash_closing_py_2', models.FloatField(default=0)),
                ('cash_closing_py_3', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
