# Generated by Django 3.1.7 on 2021-10-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshbooks_app', '0004_accountmetrics_profitmetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmetrics',
            name='cogs_py_1',
        ),
        migrations.RemoveField(
            model_name='accountmetrics',
            name='cogs_py_2',
        ),
        migrations.RemoveField(
            model_name='accountmetrics',
            name='cogs_py_3',
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='cogs_py_1',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='cogs_py_2',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='cogs_py_3',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='gross_profit_py_1',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='gross_profit_py_2',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='gross_profit_py_3',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='gross_profit_ytd',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='net_profit_p_3',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='net_profit_py_1',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='net_profit_py_2',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.DeleteModel(
            name='ProfitMetrics',
        ),
    ]
