# Generated by Django 3.1.7 on 2021-10-16 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20211015_1136'),
        ('freshbooks_app', '0005_auto_20211016_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='cogs_py_1',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='cogs_py_2',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='cogs_py_3',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='gross_profit_py_1',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='gross_profit_py_2',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='gross_profit_py_3',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='gross_profit_ytd',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='net_profit_p_3',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='net_profit_py_1',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='net_profit_py_2',
        ),
        migrations.AddField(
            model_name='accountmetrics',
            name='cogs_py_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accountmetrics',
            name='cogs_py_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accountmetrics',
            name='cogs_py_3',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ProfitMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_profit_ytd', models.FloatField(default=0)),
                ('net_profit_py_1', models.FloatField(default=0)),
                ('net_profit_py_2', models.FloatField(default=0)),
                ('net_profit_p_3', models.FloatField(default=0)),
                ('gross_profit_py_1', models.FloatField(default=0)),
                ('gross_profit_py_2', models.FloatField(default=0)),
                ('gross_profit_py_3', models.FloatField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
    ]
