# Generated by Django 3.1.7 on 2021-10-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshbooks_app', '0007_auto_20211016_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freshbooksprofitloss',
            old_name='gross_profit_py_1',
            new_name='gross_profit_1',
        ),
        migrations.RenameField(
            model_name='freshbooksprofitloss',
            old_name='gross_profit_py_2',
            new_name='gross_profit_2',
        ),
        migrations.RenameField(
            model_name='freshbooksprofitloss',
            old_name='gross_profit_py_3',
            new_name='gross_profit_3',
        ),
        migrations.RenameField(
            model_name='freshbooksprofitloss',
            old_name='net_profit_p_3',
            new_name='net_profit_1',
        ),
        migrations.RenameField(
            model_name='freshbooksprofitloss',
            old_name='net_profit_py_1',
            new_name='net_profit_2',
        ),
        migrations.RenameField(
            model_name='freshbooksprofitloss',
            old_name='net_profit_py_2',
            new_name='net_profit_3',
        ),
    ]
