# Generated by Django 3.1.7 on 2021-10-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshbooks_app', '0008_auto_20211016_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshbooksprofitloss',
            name='cogs_py_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='freshbooksprofitloss',
            name='cogs_py_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='freshbooksprofitloss',
            name='cogs_py_3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='freshbooksprofitloss',
            name='gross_profit_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='freshbooksprofitloss',
            name='gross_profit_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='freshbooksprofitloss',
            name='gross_profit_3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='freshbooksprofitloss',
            name='gross_profit_ytd',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='freshbooksprofitloss',
            name='net_profit_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='freshbooksprofitloss',
            name='net_profit_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='freshbooksprofitloss',
            name='net_profit_3',
            field=models.CharField(max_length=200),
        ),
    ]
