# Generated by Django 3.1.7 on 2021-10-16 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freshbooks_app', '0009_auto_20211016_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='cogs_py_1',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='cogs_py_2',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='cogs_py_3',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='gross_profit_1',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='gross_profit_2',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='gross_profit_3',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='gross_profit_ytd',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='net_profit_1',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='net_profit_2',
        ),
        migrations.RemoveField(
            model_name='freshbooksprofitloss',
            name='net_profit_3',
        ),
        migrations.CreateModel(
            name='ProfitMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_profit_ytd', models.FloatField(default=0)),
                ('net_profit_py_1', models.FloatField(default=0)),
                ('net_profit_py_2', models.FloatField(default=0)),
                ('net_profit_p_3', models.FloatField(default=0)),
                ('gross_profit_py_1', models.FloatField(default=0)),
                ('gross_profit_py_2', models.FloatField(default=0)),
                ('gross_profit_py_3', models.FloatField(default=0)),
                ('cogs_py_1', models.FloatField(default=0)),
                ('cogs_py_2', models.FloatField(default=0)),
                ('cogs_py_3', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
