# Generated by Django 3.1.7 on 2021-10-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshbooks_app', '0010_auto_20211016_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='cogs_py_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='cogs_py_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='cogs_py_3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='gross_profit_py_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='gross_profit_py_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='gross_profit_py_3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='gross_profit_ytd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='net_profit_py_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='net_profit_py_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='net_profit_py_3',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='ProfitMetrics',
        ),
    ]
