# Generated by Django 3.1.7 on 2021-10-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshbooks_app', '0014_auto_20211016_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshbooksprofitloss',
            name='net_profit_ytd',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
