"""empty message

Revision ID: 07f699d4a893
Revises: 
Create Date: 2019-03-28 19:28:52.451448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f699d4a893'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'account_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'account_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
