"""empty message

Revision ID: 0811448ecdd8
Revises: f47243a0d1ba
Create Date: 2020-03-23 16:34:33.345192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0811448ecdd8'
down_revision = 'f47243a0d1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'rating')
    # ### end Alembic commands ###
