"""empty message

Revision ID: 0e7a070fe266
Revises: 80aff371d405
Create Date: 2020-03-21 11:37:57.996104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7a070fe266'
down_revision = '80aff371d405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DnbJson', sa.Column('created_date', sa.String(), nullable=True))
    op.add_column('DnbJson', sa.Column('created_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DnbJson', 'created_time')
    op.drop_column('DnbJson', 'created_date')
    # ### end Alembic commands ###
