"""empty message

Revision ID: 1027488a922d
Revises: f368fb262614
Create Date: 2020-02-21 15:25:44.887471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1027488a922d'
down_revision = 'f368fb262614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'amount')
    op.drop_column('companies', 'room_number')
    op.drop_column('companies', 'other_loan_reason')
    op.drop_column('companies', 'other_industry_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('other_industry_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('other_loan_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('room_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
