"""empty message

Revision ID: 12922203a582
Revises: aba151565a07
Create Date: 2020-03-20 11:20:54.631218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12922203a582'
down_revision = 'aba151565a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rawjson', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rawjson', 'created_date')
    # ### end Alembic commands ###
