"""empty message

Revision ID: 166dbf578f75
Revises: e17ce7df0d4b
Create Date: 2020-04-21 10:39:44.906500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166dbf578f75'
down_revision = 'e17ce7df0d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('bin_number', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('experian_score_fetched_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'experian_score_fetched_time')
    op.drop_column('companies', 'bin_number')
    # ### end Alembic commands ###
