"""empty message

Revision ID: 23f6f5127608
Revises: 82fce3d15b27
Create Date: 2020-03-17 11:57:52.659950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f6f5127608'
down_revision = '82fce3d15b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'duns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('duns', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
