"""empty message

Revision ID: 2b94c4477858
Revises: 986aec4a8309
Create Date: 2020-03-20 10:49:59.254051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b94c4477858'
down_revision = '986aec4a8309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rawjson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duns', sa.Integer(), nullable=True),
    sa.Column('rawjson', project.api.models.JsonEncodedDict(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rawjson')
    # ### end Alembic commands ###
