"""empty message

Revision ID: 55263d10507c
Revises: 6c30b2fc2b50
Create Date: 2020-03-17 12:01:08.656168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55263d10507c'
down_revision = '6c30b2fc2b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('duns', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'rating')
    op.drop_column('companies', 'duns')
    # ### end Alembic commands ###
