"""empty message

Revision ID: 619799b0f94b
Revises: 1eae327af9e1
Create Date: 2020-03-13 09:42:03.081864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619799b0f94b'
down_revision = '1eae327af9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('last_time_rating_fetched', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'last_time_rating_fetched')
    # ### end Alembic commands ###
