"""empty message

Revision ID: 6c30b2fc2b50
Revises: c4382ebc719b
Create Date: 2020-03-17 12:00:50.632678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c30b2fc2b50'
down_revision = 'c4382ebc719b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'rating')
    op.drop_column('companies', 'duns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('duns', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
