"""empty message

Revision ID: 80aff371d405
Revises: ad3b613b030c
Create Date: 2020-03-21 11:23:59.767910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80aff371d405'
down_revision = 'ad3b613b030c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DnbJson',
    sa.Column('duns', sa.Integer(), nullable=True),
    sa.Column('json_data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('json_data')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DnbJson')
    # ### end Alembic commands ###
