"""empty message

Revision ID: 92d39ae17b97
Revises: f02a4f337ccc
Create Date: 2020-03-20 10:58:24.952642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d39ae17b97'
down_revision = 'f02a4f337ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rawjson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duns', sa.Integer(), nullable=True),
    sa.Column('rawjson', project.api.models.JsonEncodedDict(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rawjson')
    # ### end Alembic commands ###
