"""empty message

Revision ID: 9977cad01b1a
Revises: 952847c5f497
Create Date: 2020-03-23 15:47:48.909815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9977cad01b1a'
down_revision = '952847c5f497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('rating', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
