"""empty message

Revision ID: 99eb4d2f3de2
Revises: 07f699d4a893
Create Date: 2019-03-29 13:42:00.458780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99eb4d2f3de2'
down_revision = '07f699d4a893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banking_tokens')
    op.add_column('users', sa.Column('last_step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_step')
    op.create_table('banking_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('institution_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('institution_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='banking_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='banking_tokens_pkey')
    )
    # ### end Alembic commands ###
