"""empty message

Revision ID: aba151565a07
Revises: 92d39ae17b97
Create Date: 2020-03-20 11:08:59.821695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba151565a07'
down_revision = '92d39ae17b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rawjson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duns', sa.Integer(), nullable=True),
    sa.Column('rawjson', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rawjson')
    # ### end Alembic commands ###
