"""empty message

Revision ID: ae1e0873335b
Revises: 12922203a582
Create Date: 2020-03-20 11:22:57.792514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae1e0873335b'
down_revision = '12922203a582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dnbjson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duns', sa.Integer(), nullable=True),
    sa.Column('jsondata', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rawjson')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rawjson',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('duns', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rawjson', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rawjson_pkey')
    )
    op.drop_table('dnbjson')
    # ### end Alembic commands ###
