"""empty message

Revision ID: be95627b26ab
Revises: de14f311f311
Create Date: 2020-03-17 12:02:49.309352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be95627b26ab'
down_revision = 'de14f311f311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('duns', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'duns')
    # ### end Alembic commands ###
