"""empty message

Revision ID: c371a174b05f
Revises: 619799b0f94b
Create Date: 2020-03-19 17:00:39.942297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c371a174b05f'
down_revision = '619799b0f94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dnbrating',
    sa.Column('duns', sa.Integer(), nullable=True),
    sa.Column('dnb_rate', sa.String(), nullable=True),
    sa.Column('last_pull_time', sa.DateTime(), nullable=True),
    sa.Column('last_pull_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('dnb_rate')
    )
    op.create_table('financial',
    sa.Column('duns', sa.Integer(), nullable=True),
    sa.Column('financial_statement_todate', sa.DateTime(), nullable=True),
    sa.Column('currency_iso_alpha3_code', sa.String(), nullable=True),
    sa.Column('fiscalindicator', sa.Boolean(), nullable=False),
    sa.Column('auditindicator', sa.Boolean(), nullable=False),
    sa.Column('financial_statement_fromdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('duns')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial')
    op.drop_table('dnbrating')
    # ### end Alembic commands ###
