"""empty message

Revision ID: c4382ebc719b
Revises: 23f6f5127608
Create Date: 2020-03-17 11:58:07.086827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4382ebc719b'
down_revision = '23f6f5127608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('duns', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'duns')
    # ### end Alembic commands ###
