"""empty message

Revision ID: d21a29d99937
Revises: be95627b26ab
Create Date: 2020-03-17 14:46:10.267183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21a29d99937'
down_revision = 'be95627b26ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial',
    sa.Column('duns', sa.Integer(), nullable=True),
    sa.Column('financial_statement_todate', sa.DateTime(), nullable=True),
    sa.Column('currency_iso_alpha3_code', sa.String(), nullable=True),
    sa.Column('fiscalindicator', sa.Boolean(), nullable=False),
    sa.Column('auditindicator', sa.Boolean(), nullable=False),
    sa.Column('financial_statement_fromdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('currency_iso_alpha3_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial')
    # ### end Alembic commands ###
