"""empty message

Revision ID: de14f311f311
Revises: 55263d10507c
Create Date: 2020-03-17 12:02:33.441060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de14f311f311'
down_revision = '55263d10507c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'duns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('duns', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
