"""empty message

Revision ID: e17ce7df0d4b
Revises: 978e52e5f453
Create Date: 2020-04-08 14:20:58.776316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17ce7df0d4b'
down_revision = '978e52e5f453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('experian_score', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'experian_score')
    # ### end Alembic commands ###
