"""empty message

Revision ID: eb42f33b43d0
Revises: 0fb4326712c6
Create Date: 2020-03-12 16:26:01.335257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb42f33b43d0'
down_revision = '0fb4326712c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'rating')
    # ### end Alembic commands ###
