"""empty message

Revision ID: f02a4f337ccc
Revises: 2ba2f9fc1b20
Create Date: 2020-03-20 10:56:34.056383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02a4f337ccc'
down_revision = '2ba2f9fc1b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rawjson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duns', sa.Integer(), nullable=True),
    sa.Column('rawjson', project.api.models.JsonEncodedDict(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rawjson')
    # ### end Alembic commands ###
