"""empty message

Revision ID: f2c6214ffdec
Revises: ae1e0873335b
Create Date: 2020-03-20 11:44:47.007663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c6214ffdec'
down_revision = 'ae1e0873335b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dnbjson', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dnbjson', 'created_time')
    # ### end Alembic commands ###
