"""empty message

Revision ID: f47243a0d1ba
Revises: 1e3a17b100f8
Create Date: 2020-03-23 16:16:32.690459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47243a0d1ba'
down_revision = '1e3a17b100f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('rating', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
