"""empty message

Revision ID: f6829a8df524
Revises: 6e6764418bd5
Create Date: 2020-03-20 12:33:50.457000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6829a8df524'
down_revision = '6e6764418bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dnbjson', sa.Column('created_date', sa.String(), nullable=True))
    op.add_column('dnbjson', sa.Column('created_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dnbjson', 'created_time')
    op.drop_column('dnbjson', 'created_date')
    # ### end Alembic commands ###
