"""empty message

Revision ID: fcc97c23be52
Revises: 3b8c3b998de4
Create Date: 2020-03-24 17:15:36.925114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc97c23be52'
down_revision = '3b8c3b998de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('last_time_rating_fetched', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'rating')
    op.drop_column('companies', 'last_time_rating_fetched')
    # ### end Alembic commands ###
