"""empty message

Revision ID: fce8b4cd3315
Revises: 9936f5b80934
Create Date: 2020-03-17 15:10:08.192011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce8b4cd3315'
down_revision = '9936f5b80934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial',
    sa.Column('duns', sa.Integer(), nullable=True),
    sa.Column('financial_statement_todate', sa.DateTime(), nullable=True),
    sa.Column('currency_iso_alpha3_code', sa.String(), nullable=True),
    sa.Column('fiscalindicator', sa.Boolean(), nullable=False),
    sa.Column('auditindicator', sa.Boolean(), nullable=False),
    sa.Column('financial_statement_fromdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('duns')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial')
    # ### end Alembic commands ###
