# Generated by Django 3.1.7 on 2021-06-01 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quickbooks_Liabilities_And_Equity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts_payable', models.CharField(max_length=200)),
                ('total_accounts_payable', models.CharField(max_length=200)),
                ('total_other_current_liabilities', models.CharField(max_length=200)),
                ('total_current_liabilities', models.CharField(max_length=200)),
                ('total_long_term_liabilities', models.CharField(max_length=200)),
                ('total_liabilities', models.CharField(max_length=200)),
                ('total_equity', models.CharField(max_length=200)),
                ('total_liabilities_and_equity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuicBooks_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bank_accounts', models.CharField(max_length=200)),
                ('total_other_current_assets', models.CharField(max_length=200)),
                ('total_current_assets', models.CharField(max_length=200)),
                ('total_fixed_assets', models.CharField(max_length=200)),
                ('total_assets', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
