# Generated by Django 3.1.7 on 2021-06-01 22:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intuit', '0003_auto_20210601_2247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuickBooks_Asset',
            new_name='QuickbooksAsset',
        ),
        migrations.RenameModel(
            old_name='Quickbooks_Liabilities_And_Equity',
            new_name='QuickbooksLiabilitiesAndEquity',
        ),
    ]
