# Generated by Django 3.1.7 on 2021-10-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intuit', '0007_quickbooksassetliabilitiesandequity_accounts_recieveable'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooksassetliabilitiesandequity',
            name='total_accounts_recieveable',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
