# Generated by Django 3.1.7 on 2021-10-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intuit', '0008_quickbooksassetliabilitiesandequity_total_accounts_recieveable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickbooksassetliabilitiesandequity',
            name='total_accounts_recieveable',
        ),
    ]
