FROM node:8.8.1

RUN mkdir -p /usr/src/app/gro-client
ENV APP /usr/src/app/gro-client

COPY package.json yarn.lock $APP/
COPY src/config/env.example.js $APP/src/config/env.js

ADD tools $APP/tools

WORKDIR $APP

RUN yarn --silient
RUN yarn add pushstate-server -g --silient

COPY . .
RUN yarn build -- --release

CMD [“pushstate-server”, “dist”, “4000”]