# Generated by Django 3.1.7 on 2021-09-24 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experian_app', '0003_auto_20210924_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experian',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
