# Generated by Django 3.1.7 on 2021-09-24 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('experian_app', '0004_auto_20210924_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experian',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
